### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by crentbonway** [Flameish/Novel-Grabber#100]
so i am prob doing this wrong to preference but i cant seem to get the update feature in the library section to work
using windows 10,
the initial download and the add to library feature works.
configured with the gear icon to download new chapters and update last chapter number
when i select the download icon the program seems to freeze for a few moments and nothing happens
what am i doing wrong?

**Comment by Flameish** [comment]
There is no update function (adding new chapters to the old EPUB). 
Download new chapters will create a new EPUB of just the new chapters if the amount of releases is past the set threshold.

**Comment by xx255q** [comment]
Hey I am also having the same issue, only the first download the program does not see any new updates but if you go to automate and search link to series it shows new chapters

**Comment by Flameish** [comment]
A little explanation what the library is all about:

The idea was to keep track of new chapter releases. So the base function of the library is to check the host every so often and then, if a new chapter is released, do things (all optional).
- Download the new chapter
- Set a threshold of how many chapters need to be released before downloading them all
- Send the new chapter(s) per email to yourself
- Show a desktop/email notification that a new chapter was released

The library does these all automatically in the background if you set them via the gear icon (and library checking is activated in the settings). 

The download button (arrow on the overview) is mostly intended for people who use the library as a means to keep track of where they are in a novel and then download all new chapters after some time to catch up. It's freezing up since its downloading the chapters in the background. I will add an indicator to show that it's busy.

The "Update last chapter number" just makes it so that it set your last downloaded chapter to the newest available. Might be useful for some people to keep that disabled.

**Comment by Flameish** [comment]
Hey I reworked the Library a bit. I hope it is a bit more clear now.

**Comment by crentbonway** [comment]
thanks for the clarification and the new library look
