### ISSUE TITLE
[BUG] Manual Chapter to Chapter Exceeding Last Chapter URL

### ISSUE THREAD

**Issue by JasCU100** [Flameish/Novel-Grabber#109]
I tried to use manual chapter to chapter. It works fine at first, but it does not seem to stop crawling in the last chapter I indicated. It would still go on so I just had to make it stop grabbing chapters. I hope it would be resolved soon! 

Thank you for your efforts!

**Comment by Flameish** [comment]
Please post both links and the next chapter button css selector.

**Comment by JasCU100** [comment]
I used a novel from asianovel.net. But since the recent update, I could already download it through the automatic tab! Thank you!
But this was what I used before, for example:
First chapter URL:  https://www.asianovel.net/novels/435/chapter-1/
Last chapter URL: https://www.asianovel.net/novels/435/chapter-77/
CSS selector: a.pagination-single__left

**Comment by Flameish** [comment]
Took me a bit too see where it went wrong.  The website uses http and not https in the href so they are not equal when comparing.

![image](https://user-images.githubusercontent.com/47372220/108639272-f4bd6700-7493-11eb-86ca-da3dc44cf2ce.png)

**Comment by JasCU100** [comment]
Oh ok thank you!

**Comment by conswang** [comment]
Hi, I just ran into this problem as well and took a while to find this issue.

I used first chapter: https://cangji.net/qiangjinjiu/qiangjinjiu-c1
Last chapter: https://cangji.net/qiangjinjiu/qiangjinjiu-c4
Selector: a:has(img[src$=/wp-content/uploads/2021/08/navnext.png])
Turned out that the website's next button was redirecting from https://cangji.net/bl/qiangjinjiu/qiangjinjiu-c4 to the link above (has an extra "bl/")

Perhaps you could add a warning that the link must exactly match the link in the next chapter button? To be fair, in hindsight it seems pretty obvious

Appreciate your work!
