### ISSUE TITLE
[FEATURE REQUEST] support for scraping text from css pseudo-elements

### ISSUE THREAD

**Issue by Tsyp** [Flameish/Novel-Grabber#115]
Hi, would it be possible to add support for scraping and reconstructing paragraphs that use css pseudo-elements to substitute bits of text?

[Regressor Instruction Manual ](https://activetranslations.xyz/rim) from chapter 68 onwards is inserting text with `::before` and `::after` around normal html text using the span class to identify them, so scrapes only get the html part. Not sure if any other sites are doing this.

**Comment by Flameish** [comment]
So, it took me a while and there is no straight way to do it but it's possible with headless. 
I've added activetranslations as a new source, metadata is pretty non existing on the site so there's just the novel name. It's also pretty slow because it uses the browser to navigate/execute javascript on the site.

Just drop the .class file inside the sources folder to the others.
[Source file](https://github.com/Flameish/Novel-Grabber/files/6051369/activetranslations.zip)

**Comment by Tsyp** [comment]
I've put the .class file in the sources folder and it grabs the metadata just fine, but trying to grab chapters gets stuck on `[INFO]Starting download...`. Browser is set to headless in settings. There's no errors in the log

**Comment by Flameish** [comment]
Added activetranslations as a new source. You can use the updater to get a new version which worked for me. (Not sure what Ive changed)

**Comment by Tsyp** [comment]
Yep, works for me now as well after updating
Cheers!
