### ISSUE TITLE
[FEATURE REQUEST] Merge new chapters of library novels into previous file

### ISSUE THREAD

**Issue by Altair2169** [Flameish/Novel-Grabber#127]
**Is your feature request related to a problem? Please describe.**

Instead of downloading individual epubs of newly released chapters. I think it would be more helpful for it to add to the orignal epub or maybe merge the new epub into the old

**Describe the solution you'd like**

All newly released chapters in the library remain in one file only with the rest of the chapters

**Describe alternatives you've considered**

Maybe instead of editing the old epub, instead create a new one by merging the contents of the old one and the new one

**Comment by Flameish** [comment]
The library will now save the novel without the chapter numbers and update it going forward. EPUB only for now.

**Comment by JudahGoldstein** [comment]
Could also be useful in text mode to download different chapters as separate .txt files instead of one large file. Especially when you're downloading a few hundred chapters it makes it pretty hard to track where you left off.

**Comment by Altair2169** [comment]
Thanks for the update....but when I add a novel to the library while it does create a folder for it, it doesn't actually move the novel file into it so we have to manually do it for the library to update the file, otherwise it'll just create a new file and keep updating it. Also would it be possible to actually manually update the old files? for ex : I have a file containing chapters till 1345. but the newest chapter is 1567. So would it possible for it to scan the file and fill in the chapters which are not present?

**Comment by Altair2169** [comment]
Another thing is the library doesn't update the previous chapters , for ex a novel has 3557 chapters and a few side stories added on top of that. if anymore chapters are added but the last chapters is still the side story, it wont add the new chapters. 
case in point : https://www.wuxiaworld.com/novel/emperors-domination

**Comment by Flameish** [comment]
Good first point. I'm going to change it so that it will try to move an already downloaded file before creating a new one in the library folder.

Currently, to update and old file you would need to set the last chapter of the library to the last chapter of the old file and then restart the library, it will then say that there are so-and-so new ones. To do this you need to remove the novel from the library (not the file/folder) and then remove all chapters which are missing from the chapters list before re-adding the novel to the library. Another way would be manually editing the library.json file and setting the "lastChapter" variable.

Concerning your last question, checking and updating missing chapters is a bit more complicated and usually not needed when you download the novel fully once and then keep adding the new chapters on top. This case with the side stories at the end is unfortunate.

**Comment by Altair2169** [comment]
Yea you are right the third point is an extreme case but maybe the library can check the TOC from the website and the TOC from the file and match them to get the missing chapters? it should for all cases right? and it already does something similar when a few chapters fail to download and it downloads them at the end. Maybe you can add this as an option?

I got the JSON workaround which I used but what did you mean by 

> To do this you need to remove the novel from the library (not the file/folder) and then remove all chapters which are missing from the chapters list before re-adding the novel to the library.

?

**Comment by Flameish** [comment]
Its not quite that easy. How do you know which chapter is missing and what happens if multiple chapters have the same name? You'll need an identifier stored inside the ePub TOC NG could read and understand. I would go with the chapter URL hashed in some form added to the file name. This would make some really ugly chapter file names and some people use those. All in all it would require quite extensive changes and additions, the retry function is completely unusable for this. I will think about it, no promised yet tho.


> To do this you need to remove the novel from the library (not the file/folder) and then remove all chapters which are missing from the chapters list before re-adding the novel to the library.

![Peek 2021-03-17 23-26](https://user-images.githubusercontent.com/47372220/111546861-988af180-8778-11eb-8583-0119be084b52.gif)

**Comment by Altair2169** [comment]
yea sure that's up to you but my idea was to compare chapter numbers not the title itself, since you have source TOC stored in the url, we could simply compare the numbers with that in the file and dl the missing ones though I am sure I am really understating the complexity here

**Comment by Altair2169** [comment]
Oh and that workaround actually obliterated all the chapters except those which I had removed in the chapter list from the original file

**Comment by Flameish** [comment]
It can only add chapters right now, so I'm not sure what happened.

**Comment by Flameish** [comment]
Also you cant use the chapter number because, like in your case with the side stories, chapter insertions will mess the numbers up.

**Comment by Altair2169** [comment]
Another thing I noticed is that it actually does detect that new chapters are available for downloading despite it showing the side stores as latest chapters but again the same bug happens, it deletes all the previous content except the new chapters when I download them, it happened with another novel too. Maybe something to look at? if only that could be fixed, while yea the side chapter won't be in a neat pile at the bottom but maybe all the chapters can be added as is when they are released?

**Comment by Flameish** [comment]
NG basically just counts the links on the toc page. First link is chapter 1 and last chapter will be chapter n. If the amount of all chapter links is different to the previous time it shows that there are new chapters available and will download the latest chapter. In your case it will always be the side story since it's the last chapter on the list. This is why I mentioned that chapter number aren't unique enough. 

To understand your problem correctly, if you have a novel file already present and you download the new chapters, it will remove all old ones? That sounds to me like it creates a new file instead of modifying it. 
Can you try adding a new novel and then change the lastChapter number in the library.json so that you can try downloading the last chapter a few times?

**Comment by Altair2169** [comment]
Yep same problem and I dont think it's creating a new file, its modifying the original one
![Screenshot_317](https://user-images.githubusercontent.com/80315381/111777581-807eb380-88d9-11eb-9b75-ef8bae241dba.jpg)

**Comment by Flameish** [comment]
Closed in favor of #132 and #134
