### ISSUE TITLE
Comrade Mao Doesnt Work

### ISSUE THREAD

**Issue by RuthlessRuler** [Flameish/Novel-Grabber#13]
Trying to grab novels from comrade mao but they results in:

>  [ERROR]String must not be empty
> null
 Eg. Apotheosis, Yuan Zun and Etc! Please fix it when possible! Also can you give an example of what should be the next tag for Chapter to Chapter Manual Grabbing.

**Comment by Flameish** [comment]
I mistakenly removed it from the 'chapter-to-chapter' websites list. I will hurry and publish another release, until then you should be able to use manual grabbing for Comrade Mao.

The next chapter button field accepts a css selector. ![You can easily retrieve it if you right click on the button in your browser > inspect > right click on the html element > copy > css selector ](https://i.imgur.com/2Nqtn3E.gifv)
For Comrade Mao it would be: 
`nav.navigation:nth-child(1) > div:nth-child(1) > a:nth-child(3)`
while the chapter container is:
`article div`
The only problem on Comrade Mao with this is the very first chapter because there is one button less. (the previous chapter button) 
A better css selector which checks for something that only the next chapter button has would be:
`a.btn.btn-default.btn-sm:has(i.fa-angle-right)`

**Comment by RuthlessRuler** [comment]
Why is the chapter title missing on start of each chapter? Like Though the chapter name in case of comradeo mao isnt there, but just a heading to specify a new chapter would be appreciated.
Also, if I am downloading chapters (400 - 410 as an example), then the Chapter name in TOC should be 400 and not 1. (Chapter to chapter Manual Grabbing Bug)

**Comment by Flameish** [comment]
There is no chapter title at the start of each of chapter because it just grabs the contents of the chapter container without modifying it. I would have to create a new option to display the chapter title/chapter number since some websites do have chapter titles.

The chapter numeration always starts at 1 since it doesn't check for one in the URL/text. I could add a new field next to the 'First Chapter URL' field where you can enter the starting chapter number.

**Comment by RuthlessRuler** [comment]
Ohh. Thanks for the information. That makes sense for website that don't have chapter number in their URL like wuxiaworld.co and etc.
If Possible please implement both the option and change the Settings favicon to something more like of that of and Edit Icon as it makes it easier to understand. (Manual Grabbing)

**Comment by Flameish** [comment]
Yes. To remove certain elements from the chapter body you have to add the css selector of the element to the 'blacklisted tags'. A bunch of them are already added to auto grabbing, but you have to do each manually for manual.

![blacklisted tags](https://i.imgur.com/0j6c4EK.png)

**Comment by RuthlessRuler** [comment]
Any Updates on fixing this issue?

**Comment by Flameish** [comment]
Sorry to leave you hanging like that. I uploaded my current build as a beta version. Comrade Mao auto grabbing should work in this one.

[v2.3.0-beta](https://github.com/Flameish/Novel-Grabber/releases/tag/v2.3.0-beta)
