### ISSUE TITLE
[BUG] Unlimited Chapters per novel never happened. 

### ISSUE THREAD

**Issue by budikesuma** [Flameish/Novel-Grabber#140]
Dear devs,
"From Telegram Bots"

`Chapters left today: 1500 
Max. chapters per novel: Unlimited 
Wait time between chapters: 1000 milliseconds`

What's wrong with the bot? 
Unlimited for "Max Chapters per Novel" never happened.  
The bot still uses a quota of 1500 chapters.  This becomes awkward for me who often download RAW novels which on average contain thousands of chapters per novel, or other translated novels such as Super God Gene or Martial God Asura etc, which have reached several thousand chapters at this time.  
`Request:`
Can you Remove the 1500 chapters quota?  because other similar bots don't have a quota limit like this.  
But I prefer your bot because the results are very good.  
`One more request`, can you `Display the chapter titles` by default?  because I often forget to set it up when it's a hassle.  Reading a novel with a blank chapter title is uncomfortable.

Thanks for your hard works..

Android.
Telegram bot.

![Screenshot_20210325-043357_Telegram](https://user-images.githubusercontent.com/50254552/112387388-9af5ca00-8ce9-11eb-8e32-b234cf35ad1e.jpg)

**Comment by Flameish** [comment]
A bit of background. 

The bot is currently running on an old [Raspberry Pi](https://www.raspberrypi.org/products/) I had laying around when I added the bot. At the start it was intended as a demo showcasing the bot so that people set up their own when they liked it and ease up traffic for me. But people are lazy or don't quite know how to do it and the bot currently has over a hundred active users and over 15GB worth of novels processed. 

A while back I noticed groups and users queuing up novels with high chapter counts (like you mentioned), those novel take hours to fully finish and that doesn't even include failed chapter retries. The bot can handle around 5-10 simultaneous running downloads and something had to be done for the current setup if you add those long running novels into the mix. 

So I added a few restrictions, I asked myself how many chapters you can read in a day and low balled it to 1500 to discourage people who download multiple full length novels they can't possibly read in a single day. I also added another limit which makes it impossible to download novels which have more than a certain number of chapters, this is the value of `Max. chapters per novel`, which is currently disabled (unlimited chapters per novel).

To answer your questions, `Chapter Quota` trumps `Max chapter per novel` which is unused at the moment anyway. 
I also can't set `-displatTitle` as a default because many chapters come with a title inside their chapter text already and this would insert another above.

**Comment by budikesuma** [comment]
@flameish

how do i set the bot to be our own?

**Comment by Flameish** [comment]
There is a little bot section on the [readme](https://github.com/Flameish/Novel-Grabber/blob/master/README.md)

**Comment by damare01** [comment]
> There is a little bot section on the [readme](https://github.com/Flameish/Novel-Grabber/blob/master/README.md)

As you said there are many that who don't know how to set the bot to be their own, so can you please make a step by step tutorial on how to do so?
