### ISSUE TITLE
Flying Lines Issue Again

### ISSUE THREAD

**Issue by JasCU100** [Flameish/Novel-Grabber#16]
Hello! I can't seem to download anything from Flying Lines lately. 

This is the error code from version 2.3.1

2749 [pool-1-thread-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\pc\.m2\repository\webdriver\chromedriver\win32\........blahblah.......\chromedriver.exe
Starting ChromeDriver .........blahblah........... on port ............blahblah
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Jan 20, 2020 12:13:53 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
21549 [pool-2-thread-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\pc\.m2\repository\webdriver\chromedriver\win32\.......blahblah..........\chromedriver.exe
Starting ChromeDriver ................blahblah.................. on port ............blahblah
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Jan 20, 2020 12:14:10 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C

-------------------------------------------------------------------------------

This error code from version 2.3.2

799 [pool-1-thread-1] INFO io.github.bonigarcia.wdm.WebDriverManager - Exporting webdriver.chrome.driver as C:\Users\pc\.m2\repository\webdriver\chromedriver\win32\.......blahblah.........\chromedriver.exe
Starting ChromeDriver .......................................... on port .........blahblah
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Jan 20, 2020 12:17:47 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Exception in thread "pool-1-thread-1" java.lang.NullPointerException
        at java.io.StringReader.<init>(Unknown Source)
        at org.jsoup.parser.Parser.parse(Parser.java:107)
        at org.jsoup.Jsoup.parse(Jsoup.java:58)
        at grabber.AutoNovel.getChaptersHeaderless(AutoNovel.java:320)
        at grabber.AutoNovel.getChapterList(AutoNovel.java:175)
        at grabber.AutoNovel.<init>(AutoNovel.java:94)
        at gui.GUI.lambda$null$5(GUI.java:274)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

I currently use version 2.3.1 because I find the previous one more stable for me. For version 2.3.2, Chrysanthemum G  would not display the Title and Author....it's only left as Untitled and I prefer not to use a headerless browser. 

This is my go-to novel downloader lately and I hope that this would be resolved soon. Thank you very much for your hard work!

**Comment by Flameish** [comment]
You can edit Title, Author, Cover, Tags and Description if you click on the gear icon. 
I fixed the selectors for CG again (since I broke them with a overzealous search-and-replace previously).

On the other hand, Flying-Lines gives me problems aswell. I personally don't have a problem with fetching the novel info (which seems to be the part where you're stuck), but loading the chapter page. I need to do more testing to pin point the issue (I'm playing around with the idea that they're detecting and blocking the headerless browser since every other page except the chapter one is working fine).
Going back to the previous method of fetching the chapter content via api-call doesn't work either easily anymore since they're encrypting the chapter content now (if im not totally wrong).
![image](https://i.imgur.com/2kRlSlo.png)

I will hotfix-y release v2.3.3 which has the fixed selectors for CG (and other unfortunate sites)

**Comment by JasCU100** [comment]
Oh, thank you for the update! It has fixed the titles, etc. I'm looking forward to the next updates regarding the flying lines issue. Thank you for the quick response!
