### ISSUE TITLE
[BUG] Last chapter is set to the same one as Newest chapter after downloading e.g. 8 out of 40 chapters

### ISSUE THREAD

**Issue by Kapperhino** [Flameish/Novel-Grabber#160]
So basically if I try to download this. (Yes, I tried it on other sites. Its just an example)

![image](https://user-images.githubusercontent.com/19327337/113614225-82bf6c80-9652-11eb-9814-e484f8b899cc.png)

and then add it to the library

![image](https://user-images.githubusercontent.com/19327337/113614282-94a10f80-9652-11eb-9414-78d06feda3f2.png)

It just sets the Last chapter to 1630 instead of 8

Alternative to fixing it could be adding an option which allows you to select your last read chapter from a list of chapters.

**Comment by Flameish** [comment]
This is intended behavior, it doesn't take the last downloaded chapter into consideration. Since ideally you download everything once / get caught up and then add the novel to the library to get the new releases. Why would you care that chapter 3463 was released when you're at 8 afterall?

And you already answered your own question. You can remove all unwanted chapters from the chapter list manually and then add the novel to the library, it will set the last chapter to 8 since that's the latest. You then have to restart the library or wait for the next polling interval to get the actual latest number. Same goes for metadata like cover and title.

**Comment by Kapperhino** [comment]
Oh, I didnt know that it was supposed to work like that but its actually reasonable.
Thanks for the tip in the second paragraph though. I didnt know that you could do it like that.
