### ISSUE TITLE
Error while creating epubs on Mac

### ISSUE THREAD

**Issue by carlobonandrini** [Flameish/Novel-Grabber#23]
I am trying to create an epub of a novel from Wuxiaworld (tried from Royalroad, too) on mac (java 8). If i export it as an epub then when i try to open it on iBooks it gives me an error because the file is damaged. If i try to export to calibre, when i convert it (like it is shown in the readme), the chapter are all out of order.
Any ideas?

**Comment by Flameish** [comment]
Can you open the EPUB with the eBook reader of Calibre? I think it might be the same issue from #22.

**Comment by carlobonandrini** [comment]
Yeah I think it is the same error, i can open it Calibre. Do you have something planned to fix it or is there nothing to do about it? Because i read on ipad and there aren't good alternatives to ibooks.
What about the error in calibre where all the chapters are out of order? Did it ever happen?
Thanks for everything!

**Comment by Flameish** [comment]
I'm planning to discontinue the Calibre export option since you can convert the EPUB in Calibre too, so I can't really help you there. A HTML cleaner/sanitizer is planned. For now you could try to convert the EPUB file in Calibre to some other format (and back if needed). Alternatively you could fix the broken EPUB with Sigil if its on Mac (like in the issue described).
