### ISSUE TITLE
Can't open

### ISSUE THREAD

**Issue by azurymous24** [Flameish/Novel-Grabber#298]
Hi! I just want to ask why I can't open or launch my Novelly. Here are the screenshots. It can't be open directly so I tried opening it via cmd, but it would only say unable to access. I've downloaded this Java (jre-8u301-windows-x64) . Please tell me if there's something I'm lacking. I apologize as I'm still new to installing this.

![image](https://user-images.githubusercontent.com/73337125/135480361-7598eee3-ed6d-4668-bfb7-807c49e09ceb.png)

![Screenshot 2021-09-30 22 55 58](https://user-images.githubusercontent.com/73337125/135480082-6e07c640-8246-4612-84b7-9b4a0605d0ae.png)

![Screenshot 2021-09-30 22 55 38](https://user-images.githubusercontent.com/73337125/135480068-dc5117b9-651a-41ed-bcfc-6ece0c991d2a.png)

**Comment by Flameish** [comment]
It can't find the jar since you are in the wrong folder in Powershell. Its currently working in `C:\\Users\USER` while the jar is in `C:\\Users\USER\Downloads\Novel-Grabber\`. I would try shift+right clicking in the novel-grabber folder, the "open Powershell here" menu option should be available. Alternatively you could do `java -jar \Downloads\Novel-Grabber\NG-Launcher.jar` but it can be a bit wonky when using that (creating config files where you opened powershell etc.).

**Comment by azurymous24** [comment]
Thank you so much for the reply. I tried the Powershell option and it worked. :) :)
