### ISSUE TITLE
Issue with WuxiaWorld and Webnovel

### ISSUE THREAD

**Issue by renatopdalencar** [Flameish/Novel-Grabber#31]
Hello there!

First of all, I would like to thank you for the wonderful application and all the work you've put into it.

I'm facing a problem with WuxiaWorld on Novel Grabber that is the access to VIP-only chapters. For example, I Shall Seal The Heavens from chapter 101 and forward is locked to VIP users, and so they appear on the ebook generated by Novel Grabber like this
![issthissue](https://user-images.githubusercontent.com/65918656/82836068-3769f880-9e9c-11ea-9560-e016f622939b.png)

Is there any way to fix this? I tried using Webnovel, but although Webnovel lists 1611 chapters, Novel Grabber only identifies 40, since chapters 41 and forward require coins.

**Comment by Flameish** [comment]
This is not a bug since I won't support grabbing of VIP/locked content without providing an account where these have been unlocked. Sorry.
If this is what you mean, I might implement it depending on popular demand.

**Comment by C0rn3j** [comment]
If I understand correctly there's still no way to supply a webnovel.com account with unlocked content?

Is there a list which sites ARE supported with the account feature?

I tried adding the cookies to Webnovel but it was still only able to see the free chapters.

**Comment by Flameish** [comment]
Webnovel not being supported was the old version. Every supported site can theoretically use login.

1. Pick your source in the settings
2. Click on "Get Cookies" 
3. Login like normal 
4. Close the browser window
5. Select "Use account" before fetching novel info/chapter list

Worked on Webnovel the last time I tried it. If it still kot working please send the error log.

**Comment by C0rn3j** [comment]
That's exactly what I tried, with my google account, for https://www.webnovel.com/book/omniscient-reader_12524375106746605

the 3.4.0 client claims there's only 42 chapters even after doing so, although I do have 44 unlocked.

There's no error log associated with this, nothing in the terminal, and the app just lets me download the first 42 chapters.

![image](https://user-images.githubusercontent.com/1641362/108560729-7af37500-72fd-11eb-8eb6-4f8ba6a9097a.png)

The cookies are there

**Comment by Flameish** [comment]
Going to take another look.

**Comment by Flameish** [comment]
So, it wouldn't fetch the unlocked chapters the first time around but after I redid the login it worked. I'm also using email to log in but that shouldn't matter.

 Did you by chance open the open browser via Get Cookies again? Because that would overwrite the cookies. (It always starts without cookies)

**Comment by C0rn3j** [comment]
Hmm I think this has something to do with the `Use account` button in combination with launching the app for the first time.

I had it checked previously, and the app would happily show 42 chapters.

I relogged (with an email account), checked the box, and now I get my 44.

Now if I uncheck it and delete the cookies, the app will tell me to GTFO in the log with an error instead of going through and not actually working.

**Comment by Flameish** [comment]
Going to try to replicate that. Thanks!

**Comment by Flameish** [comment]
Do you mean the very first time after installing? Because selecting `Use Account` with no accounts file works without crashing.

Concerning the last part, the problem were the deleted cookies. When you remove all lines(cookie name/value pairs) it still stored one empty pair from the textbox and it throws: `IllegalArgumentException: Cookie name must not be empty` when trying to login.
I've added a check for this now and will be in the next update sometime soonish.

**Comment by C0rn3j** [comment]
>Do you mean the very first time after installing?

I think so, I never used this app before, but am not 100%.

>Concerning the last part, the problem were the deleted cookies. 

Ah, that explains it!

**Comment by C0rn3j** [comment]
Well I think I figured out the other issue - I assumed the cookies get saved on browser close, but it seems you have to do it through a "Save cookies" button which replaces the "Open browser" button, which I didn't notice at first.

Wouldn't it be better to put the Save cookies button in the middle here, and grey it out if it's not available?

![image](https://user-images.githubusercontent.com/1641362/109132438-22d0ce80-7754-11eb-93cf-3cbba57ead89.png)

**Comment by Flameish** [comment]
No, the Save Cookies button is new. It shows up after the browser window is loaded.

From the changelog file:

3.4.1 - 2021-02-20
=====
- Fixed login for Royal Road
- Fixed headless grabbing for manual grabbing
- Fixed a bug which prevented login when manually deleting all cookies for a source
- Added a dedicated "save cookies" button for logins
