### ISSUE TITLE
Site request

### ISSUE THREAD

**Issue by zpereyra** [Flameish/Novel-Grabber#33]
Hi,
I would like to request a possibility of logging in on websites that have VIP/Paid stories. Also, if you can include booklat.com.ph as a source.

Do you have any plans on porting this as a telegram bot? 

Thanks.

**Comment by Flameish** [comment]
I already mentioned the logging feature as a possibility on other questions, I just put it off because of lacking interest until now. Looking at booklat, it would seem that this feature is needed to support the site or am I missing a way to read while not being logged in?

I have no current experience with telegram bots or telegram in general, so that would be a no without further research for now. Sorry.
I do plan to port it as an app or potential web service at some point through.

**Comment by zpereyra** [comment]
You are correct in booklat site. One needs to be logged in to access the site.

Making it as a web service or as an app will be nice. I just thought of telegram as the files can be easily stored in their server by the person pulling the books. But all in all, you have a great project. Thank you.

**Comment by Flameish** [comment]
I've added initial account support and support for booklat. Check out 2.6.0.

**Comment by zpereyra** [comment]
Thank you. I'll check it out and update you

**Comment by zpereyra** [comment]
Booklat works like a charm. Thank you. Is it possible to have the rendered book filename as title - author?

**Comment by Flameish** [comment]
Done. Will be in the next release.

**Comment by zpereyra** [comment]
Very much appreciated!
