### ISSUE TITLE
Novel Titles

### ISSUE THREAD

**Issue by JasCU100** [Flameish/Novel-Grabber#35]
Hello! It seems like the latest release saves the epub titles wrong. Like for CG, I would name the epub <Title> but the resulting epub would be "Unknown" <Title>. It seems like Boxnovel also has this but with the author instead of "Unknown". I'm not sure if other sites also have this issue though. Thank you!

**Comment by apaxc** [comment]
I myself had this problem for the longest time. But yesterday as I was looking for some novels in BoxNovel I realized BoxNovel already has added chapter names in the chapters themselves.

So what I did was when in Novel Grabber I removed " Add chapter title ", and now I have the chapter names showing up and TOC working properly.

![Novel Grabber](https://user-images.githubusercontent.com/64091461/86446855-2de67280-bd1d-11ea-8af3-0a8ff01cb891.png)


**Option for adding chapter title should be removed for Box Novel as it seems to cause a lot of problems.**

**Comment by Flameish** [comment]
@JasCU100 The EPUB file naming convention is [author] - [title] since 2.7.0. If NG can't find the author / title it will show them as "unknown" on the interface. Some sites are pretty bad for grabbing these kind of info since they're not uniform. So I just leave that particular selector out.

Example CG:
![image](https://i.imgur.com/j2ojw7P.png)
As you can see the novel-title is in it's own container making it easy to select by it's class, the author is just put as normal text in the novel-info container. It's not impossible to select but can get ugly when another novel doesn't have the same structure.

You can always edit the metadata if something doesn't match up:
![image](https://i.imgur.com/Jq5AAnf.png)

@apaxc The checkboxes are optional and not all are needed for every host site / manual grab. The `Add chapter title` option was added because some novels did not put the titles in the chapter body.
