### ISSUE TITLE
Option to redownload entire series

### ISSUE THREAD

**Issue by xx255q** [Flameish/Novel-Grabber#42]
This is due to an issue Where I originally had a series download to a network drive but in the library it set all future downloads instead to c/user/novel-grabber-series. I don't know why this happened or if I just forgot to do something. Now comes the issue: Even if I set up it correctly now every series up to till will be missing chapters in the original location. So I either need a way to re-download the entire series or the program needs to be able to scan a folder and see what is missing.

Also there seem to be some folder bug: when a new chapters were added it created to folders. Ex: for Martial God Asura there was one 'Martial" folder and a 'Martial God Asura" folder. Martial had the actual chapters and the other pictures. Overgeared did not have this issue so I assume its a bug with more than one word

**Comment by Flameish** [comment]
I really don't understand the first part. The whole point of NG is to download a complete "series". Whats stopping you from going to the automatic tab and grabbing the complete novel? NG won't be able to scan for missing files because it was never designed to work with multiple files in the first place, the core functionality is to create a single ebook file with all chapters combined.

All downloads from the library auto grabbing is saved at the location you mentioned by default, you can change it by clicking on the gear icon of the novel in the library and adjusting the -path argument (see CLI commands).

The one word folder naming was a bug from 2.8.0 and is fixed in 2.8.1. So it's probably just an old folder.

**Comment by xx255q** [comment]
It looks like if there is a space in the folder name "Chinese Novels" it
can't figure it out and will create a new "Chinese" folder

**Comment by Flameish** [comment]
It can't work with spaces in the path variable right now, that's why all created folder have "-" in them.
