### ISSUE TITLE
Temporal folder

### ISSUE THREAD

**Issue by captain-muchiko** [Flameish/Novel-Grabber#55]
Hello,
Is the temporary folder that was created when manually downloading novels no longer visible? It was useful when I wasn't sure if the chapter container that I entered was correct and it allowed me to quickly visualize the content of the html in case of just downloading an empty html body. 

Thank you.

**Comment by Flameish** [comment]
Hi! No temp files are being written to disk since 3.0.0, sorry. I can add the page counter to the manual tab, that's how I normally see if its working. How would you feel about a preview window where you can select a chapter and see what it would grab with the entered container (probably just pure text)? 

On a side note since it seems like you use manual often: How is the automatic chapter detection working for you?

**Comment by captain-muchiko** [comment]
The preview window sounds very useful, really. I will be eternally grateful if this option becomes a reality. :)

Regarding the automatic detection tool, I honestly haven't tried it yet but if it's smart enough to remove the comment/reply tag and the navigation links that are usually contained at the end of the entry-content/content class of the html, I'd love it since I spend a lot of time playing with the blacklisted tag option  and rarely have success removing irrelevant additional content.

**Comment by Flameish** [comment]
Check out 3.1.0. The preview window will take blacklisted tags and chapter container/auto detection into account.
