### ISSUE TITLE
Automatic and Manual download from W*ttP*d not working

### ISSUE THREAD

**Issue by captain-muchiko** [Flameish/Novel-Grabber#61]
Hi!
I am currently using version 3.1.1 and I'm having trouble downloading from WP. I tried automatic and manual mode, and in the two options it does not download. At first I thought it might be the Chinese characters in the URL, but it is not working with any of the URLs of the stories I have (and were working just fine in Novel Grabber a couple of weeks ago). 

In fact, the manual download log shows this when pasting an WP url: [ERROR] null

Do you know if there is currently any issue with download from that site?

As always, thank you so much for this giving us this amazing tool. :)

![manual_download](https://user-images.githubusercontent.com/70033107/97172751-3f410800-176e-11eb-9e4b-83b6ebdc1949.JPG)

**Comment by Flameish** [comment]
It seems like WattPad is using Cloudflare to block the static requests as of late. (Or it's just temporary) For most other sites you could just check the "headless browser" option to bypass that. But headless grabbing is disabled for Wattpad by default (on the automatic tab). I will fix this in the next version.

Here is something you could try:
Go to the manual tab and select "Use Headless Browser" before fetching the table of contents page. (You need to set your installed browser in the settings if you haven't used it yet) Then remove all unwanted links like usual. Select automatic chapter container detection and try to preview a few chapters to see if everything is getting fetched correctly. 
There is one caveat through: WattPad splits large chapters into several parts which get loaded when you scroll down. This is the reason why headless grabbing is disabled since it can't do that. Normally NG builds the full chapter text itself in the background. So if your chapters are not that long ( check a few with the preview option) you might be in luck.

**Comment by captain-muchiko** [comment]
I'll try those options then, thank you for the reply. :)

**Comment by captain-muchiko** [comment]
I didn't want to open a new issue since it's related to Automatic/Manual download, but it appears that chrys*nth*mung*rden is not working now either, I'm having the same issue. Maybe they did something on their website recently too? So sad. uwu

**Comment by captain-muchiko** [comment]
Oh, CG it's fixed now. Maybe it depends on the website traffic or something?

![Captura](https://user-images.githubusercontent.com/70033107/98661558-5f9fc380-2325-11eb-874c-be30acd96061.JPG)

**Comment by Flameish** [comment]
That first image you posted is the Clouflare bot protection, some websites have it on permanently and some just when there is heavy traffic. In the past you could use the headless browser option to bypass it but recently it seems like Cloudflare changed their bot detection and the headless browser is getting detected aswell.

**Comment by Flameish** [comment]
Fixed in 3.2.0
