### ISSUE TITLE
Comrademao issue

### ISSUE THREAD

**Issue by mp3096** [Flameish/Novel-Grabber#63]
Comrademao 
novel - https://comrademao.com/novel/hacker/
Stuck on fetching novel ......

Another suggestion or option
for example option to make volume of chapters like 1 to chapter 50 in same file then move on to another 51-100 and so basically saving separate file in chapter bulk rather than whole 1 file.

also can u add support for https://www.novelhall.com/

which is famous currently thank you for working hard on this project.

**Comment by Flameish** [comment]
I'm having problems reaching comrademao myself right now. They seem to have server problems. Try to use headless grabbing to bypass the Clouflare check.

Can you elaborate a bit on why splitting is necessary? It sounds counter productive to me. 

I will take a look at novelhall.

**Comment by croooked01** [comment]
I am having the same problem on Comrademao.Both with or without Headless it gets stuck on Fetching novel info..............
It only started happening since a dozen days ago,before that it was working fine!

**Comment by croooked01** [comment]
> I'm having problems reaching comrademao myself right now. They seem to have server problems. Try to use headless grabbing to bypass the Clouflare check.
> 
> Can you elaborate a bit on why splitting is necessary? It sounds counter productive to me.
> 
> I will take a look at novelhall.

I am having the same problem on Comrademao.Both with or without Headless it gets stuck on Fetching novel info..............
It only started happening since a dozen days ago,before that it was working fine as I frequently use Comrademao!

**Comment by Flameish** [comment]
It seems like Cloudflare changed their bot detection and the headless browser is getting blocked. I have not found a way around that yet.

**Comment by croooked01** [comment]
Is the problem because of Cloudflare or is it something else?Because before even without using Headless browser as long as I go to Comradeamao on my web browser and solve the captcha/puzzle on the cloudflare and then after that opening the Novel Grabber, then even without ticking the Headless browser I could access the novel info. and download the desired novel but now nothing works.Cloudflare bot detection page only shows up once every 24-48 hours and as long as you solve it on web browser then even wothout using the headless browser option it used to work but now nothing works,i.e,with or without using the headless browser.

**Comment by Flameish** [comment]
Closed in favor of #65
