### ISSUE TITLE
Comrademao

### ISSUE THREAD

**Issue by StormerIls** [Flameish/Novel-Grabber#77]
I have this error each time i try to grab from comrademao
[ERROR] Service Unavailable! (503)

**Comment by Flameish** [comment]
Error 503 means that the server has a problem/denies the request. This is probably because of Cloudflare.
See #65

**Comment by johnbeck0000** [comment]
will the problem solved if the cloudflare issue resolved

**Comment by Flameish** [comment]
It's one and the same issue: Cloudflare's bot protection

**Comment by croooked01** [comment]
Looks like this cloudflare problem is not going to be fixed anytime soon.I am using epubpress to make epubs of comrademao chapters.The only drawback is that I can only make epub of 40-50 chapters in one go.

**Comment by HarmonLucifer** [comment]
Any help on this? I live in a place where internet cuts of regularly so I need to download my Webnovels, and I really like Comrademao

**Comment by croooked01** [comment]
I haven't gotten any Cloudflare checks on Comrademao for a week. Is the Cloudflare check on Comrademao gone? But I still can't access the Comrademao urls through Novel Grabber............

**Comment by Flameish** [comment]
Thanks for the info. The "normal" requests still get blocked by Cloudflare but headless works for now. Just update, it uses it by default.

**Comment by joecheung1** [comment]
Can you add a resume button to continue where it was interrupted by a cloudflare prompt or to save what it has already downloaded?  Currently in the headless window when cloudflare pops up, the downloading will be stop and every chapter that has been save will be lost and I'll have to start over from chapter 1.

**Comment by Flameish** [comment]
What do you mean with "the downloading will be stopped"? I've never had a Cloudflare window pop up mid download before so I can't tell what's happening. (I usually test with downloading ~10 chaps and even after trying 100+ today, none showed up for me) I would guess it gets stuck on the Cloudflare page? 

Normally if a chapter fails to download because of connection errors or if it couldn't find the chapter container, NG will still output the EPUB sans missing chapters. If this is what happens I can only suggest trying to download in chunks and combine the EPUBs in Sigil/Calibre etc. for now. 

I'll see what I can do about a `re-try failed chapters` function.

**Comment by joecheung1** [comment]
This sometime happen I'm downloading a story with 800+ chapters the cloudflare page will appear in the headless window.  The program say it will retry for 30 sec but after waiting for several minutes nothing will happened.

**Comment by Flameish** [comment]
A retry failed chapters option has been added. Hope it helps.

**Comment by joecheung1** [comment]
Thanks, this will save a lot time if I don't have to restart from chapter 1.
