### ISSUE TITLE
Possible Bot or Extension

### ISSUE THREAD

**Issue by azurymous24** [Flameish/Novel-Grabber#80]
Hi! I just wanna ask if it's possible to create a discord/telegram bot for novel grabber or chrome extension? I mostly use my phone because my pc broke so I'm looking for alternative ways to download/create epub. Thanks for the answer!

**Comment by Flameish** [comment]
Possible? Sure, but not by me for the moment. Never worked with either. Sorry.

**Comment by Flameish** [comment]
I lied. Here you go: [@NovelGrabbyBot](https://t.me/NovelGrabbyBot)
Be advised that I quickly threw this together and it's certainly not finished or bug-free. (Error reporting is non existent)To use it you just have to send a novel url to it.

**Comment by azurymous24** [comment]
Thank you so much! I'll try it right now.

**Comment by Flameish** [comment]
Ops. Yeah, that's my fault. 
![image](https://i.imgur.com/Feh3Duj.png)

**Comment by azurymous24** [comment]
Does it have a chance that you'll enhance the bot or it will stay the same?

**Comment by Flameish** [comment]
You can't see it but it's already better than the very first version. Putting in lots of work into it right now.

**Comment by azurymous24** [comment]
Really?! Thank you very much! 🥰🥰🥰

I would like to suggest a few things;

1. To have an option to choose how many chapters to download either “All Chapters" or “ Chapter *insert number* to Chapter *insert number*

2. To have the bot a closing message after uploading the epub like, “Operation finished. Please input new link" or something related as closing remark.

3. To also add a message after the link has been sent to the bot like “Your epub is on process, please wait for a while." So that the user will not be confused if the bot is still running or not especially if the user decided to download a lot of chapter where the bot will take a whole while before it finish creating and uploading the epub and if they sent words or jumbled letters just to test the bot if it's still online while the epub is still on process you can add “Please wait the epub is still not yet finished" to avoid the users sending new link to the bot.

4. To have a starting message like , “Welcome *name* the bot is currently online" before  the option/command that you've given to the bot.

That's it, it's just mostly messages. My reason for wanting to suggest the above mention is to make the bot more friendly to the user.

**Comment by Flameish** [comment]
1) Already in the works. Basically I plan to port a trimmed down version of the CLI calls:

Parameter | Arguments | Description
-- | -- | --
-link | {novel_URL} | URL to the novel's table of contents page. Starts download.
[-chapters] | {all}, {5 27}, {12 last} | Specify which chapters to download.
[-noDesc] |   | Don't create a description page.
[-removeStyle] |   | Remove all styling from chapter body.
[-getImages] |   | Grab images from chapter body as well.
[-displayTitle] |   | Write the chapter title at the top of each chapter text.
[-invertOrder] |   | Invert the chapter order.

An advanced download command would look like this for example: 
`-link https:yourhost.com/novel/ -chapters 5 last -displayTitle`

2) I would wager getting the finished EPUB file is closing remarks enough but this will tie into 3) aka better status/error reporting. What's the bot doing at the moment? Did it crash? What chapter is it working on right now... etc. 
Also each user is limited to one concurrent download right now. If you try to send a 2nd link while the first one is still in progress it will say that you have to wait.

4) If the bot is not answering you, it's not online. 

5) I've actually removed that at some point since I figured that most e-readers can just display the cover image whenever you want.

**Comment by Flameish** [comment]
I also plan to add parts of the library function so that you can get messages when a new chapter of a followed novel was released.

**Comment by azurymous24** [comment]
Thank you so much for the response! The bot will be perfect in no time. Also, about the cover image, I got it.

Thank you so much for creating the bot and taking your time enhancing it. 🥰🥰🥰

I have no other issue right now, so I'll close this.

**Comment by that-wawa** [comment]
@Flameish , I downloaded Novel Grabber.zip file but I don't know what to do. Can you please guide me step by step on how to launch the novel grabber so i can read my novels from webnovels without paying. Please note that i don't have any prior programming experience..... I hope to hear from you.
